// <auto-generated />
using System;
using Colaboradix.Infra.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Colaboradix.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210409133713_InitialModel")]
    partial class InitialModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Colaboradix.Domain.Entities.Cycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("From")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("from");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTime>("To")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("to");

                    b.HasKey("Id")
                        .HasName("pk_cycles");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_cycles_team_id");

                    b.ToTable("cycles");
                });

            modelBuilder.Entity("Colaboradix.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CycleId")
                        .HasColumnType("uuid")
                        .HasColumnName("cycle_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("message");

                    b.Property<byte>("Quantity")
                        .HasMaxLength(3)
                        .HasColumnType("smallint")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiver_id");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("sender_id");

                    b.HasKey("Id")
                        .HasName("pk_feedbacks");

                    b.HasIndex("CycleId")
                        .HasDatabaseName("ix_feedbacks_cycle_id");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("ix_feedbacks_receiver_id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_feedbacks_sender_id");

                    b.ToTable("feedbacks");
                });

            modelBuilder.Entity("Colaboradix.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("active");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<byte>("Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)2)
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_members_team_id");

                    b.ToTable("members");
                });

            modelBuilder.Entity("Colaboradix.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("active");

                    b.Property<string>("Description")
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("Colaboradix.Domain.Entities.Cycle", b =>
                {
                    b.HasOne("Colaboradix.Domain.Entities.Team", "Team")
                        .WithMany("Cycles")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("fk_cycles_teams_team_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Colaboradix.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("Colaboradix.Domain.Entities.Cycle", "Cycle")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CycleId")
                        .HasConstraintName("fk_feedbacks_cycles_cycle_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Colaboradix.Domain.Entities.Member", "Receiver")
                        .WithMany("ReceivedFeedbacks")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("fk_feedbacks_members_receiver_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Colaboradix.Domain.Entities.Member", "Sender")
                        .WithMany("SubmittedFeedbacks")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("fk_feedbacks_members_sender_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Colaboradix.Domain.Entities.Member", b =>
                {
                    b.HasOne("Colaboradix.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("fk_members_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Colaboradix.Domain.Entities.Cycle", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("Colaboradix.Domain.Entities.Member", b =>
                {
                    b.Navigation("ReceivedFeedbacks");

                    b.Navigation("SubmittedFeedbacks");
                });

            modelBuilder.Entity("Colaboradix.Domain.Entities.Team", b =>
                {
                    b.Navigation("Cycles");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
